#!/bin/bash
# /etc/init.d/robot_btn

### BEGIN INIT INFO
# Provides:          robot_btn
# Required-Start:	$network
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       This service is used to manage a robot_btn
### END INIT INFO

case "$1" in
	start)
		nohup stdbuf -oL python /home/pi/robot_btn.py >/home/pi/logs/robot_btn.log 2>&1 &
		;;
	stop)
		sudo killall python
		;;
	*)
		exit 1
		;;
esac

exit 0

